# name of the file that will be used as topology by PyInteraph
# (this file will not be created if a reference structure is passed by the user,
# since the user-provided topology will be used as topology in this case)
pyintop: top.gro
# name of the file that will be used as reference by PyInteraph
# (this file will not be created if a reference structure is passed by the user,
# since the user reference structure will be used as reference)
pyinref: ref.pdb

# resampling options
resampling:
  # whether to run a resampling
  run: True
  # resampling method
  method: jackknife
  # number of samplings to be performed
  nsamplings: 5
  # names of the directories where the analyses for the full trajectory
  # or the resampled trajectories (if any) will be performed
  dirnames:
    trj: fulltrj
    # {nsampling} is a placeholder for each sampling number (that
    # goes from 0 to nsamplings-1)
    subtrj: resampling{nsampling}

# pyinteraph options
pyinteraph:
  # hydrophobic contacts options
  hc:
    # whether to run the hydrophobic contacts analysis
    run: True
    # distance cut-offs to test
    dcuts: !!seq [5.0, 5.5]
    # name of the output/log file
    out: hc.log
    # options to be passed directly to the pyinteraph command
    options:
      --ff-masses: charmm27
      --verbose: True
      --hydrophobic: True
      --hc-residues: ALA,ARG,ASN,ASP,CYS,GLN,GLU,HIS,ILE,LEU,LYS,MET,PHE,PRO,SER,THR,TRP,TYR,VAL
      --hc-dat: hc.dat
      --hc-graph: hc-graph.dat
  sb:
    # whether to run the salt bridges analysis
    run: True
    # distance cut-offs to test
    dcuts: !!seq [4.0, 4.5, 5.0]
    # salt bridges mode
    modes: !!seq [different_charge]
    # name of the output/log file
    out: sb.log
    # options to be passed directly to the pyinteraph command
    options:
      --ff-masses: charmm27
      --verbose: True
      --salt-bridges: True
      --sb-dat: sb.dat
      --sb-graph: sb-graph.dat
  hb:
    # whether to run the hydrogen bonds analysis
    run: True
    # distance cut-offs to test
    dcuts: !!seq [3.5]
    # hydrogen bonds modes (classes)
    modes: !!seq [mc-mc, sc-sc, mc-sc, all]
    # name of the output/log file
    out: hb.log
    # options to be passed directly to the pyinteraph command
    options:
      --ff-masses: charmm27
      --verbose: True
      --hydrogen-bonds: True
      --hb-dat: hb.dat
      --hb-graph: hb-graph.dat

# filter_graph options
filter_graph:
  # name of the output/log file
  out: filter_graph.log
  # persistence cut-offs to test
  pcuts: !!seq [50.0]
  # options to be passed directly to the filter_graph command
  options:
    --output-dat: filtered_graph.dat

# graph_analysis options
graph_analysis:
  hubs:
    # whether to find hubs
    run: True
    # name of the output/log file
    out: hubs.log
    # options to be passed directly to the graph_analysis command
    options:
      --hubs: True
      --hubs-cutoff: 3
      --hubs-pdb: hubs.pdb
  cc:
    # whether to find connected components
    run: True
    # name of the output/log file
    out: cc.log
    # options to be passed directly to the graph_analysis command
    options:
      --components: True
      --components-pdb: cc.pdb